"""
Synthetic sign-in log generator and ingestion script.

Simulates a brute-force sign-in attack pattern (MITRE ATT&CK T1110 - Brute
Force): four failed sign-ins followed by one success, same source IP and
account, over a short time window. Pushes the synthetic JSON records into a
custom Log Analytics table via the Azure Monitor Logs Ingestion API.

All data generated by this script is synthetic / self-generated for a
personal SOC home-lab exercise. No real user accounts, IP addresses, or
credentials are involved.

Auth: uses AzureCliCredential, i.e. whichever account you're signed into via
`az login`. That account must hold the "Monitoring Metrics Publisher" role
on the target Data Collection Rule (see README in this repo for how that
role assignment was set up).

Usage:
    pip install azure-identity azure-monitor-ingestion
    az login
    az account set --subscription "Azure for Students"
    python ingest_synthetic_signins.py
"""

import datetime
import sys

from azure.identity import AzureCliCredential
from azure.monitor.ingestion import LogsIngestionClient
from azure.core.exceptions import HttpResponseError

# ---- Configuration -----------------------------------------------------
# Values specific to this lab's Data Collection Endpoint / Rule / table.
DCE_ENDPOINT = "https://dce-sentinel-lab-mv25.francecentral-1.ingest.monitor.azure.com"
DCR_IMMUTABLE_ID = "dcr-f6356b4f338f474186ea4ef6b8ccfc96"

# Confirm this against the DCR's "streamDeclarations" key (Export template /
# JSON view in the portal) before running. It is usually "Custom-<TableName>".
STREAM_NAME = "Custom-SyntheticSignins_CL"

# Synthetic test data - not real identities or infrastructure.
SYNTHETIC_USER = "j.carter@contoso-lab.com"
SYNTHETIC_SOURCE_IP = "185.220.101.47"
SYNTHETIC_APP = "Office 365 Exchange Online"


def generate_bruteforce_logs() -> list[dict]:
    """Build a synthetic brute-force sign-in pattern.

    4 failed sign-ins ~17 seconds apart, then 1 success, all from the same
    source IP and user account - a simple stand-in for MITRE ATT&CK T1110
    (Brute Force) telemetry.
    """
    base_time = datetime.datetime.now(datetime.timezone.utc)

    def iso(offset_seconds: int) -> str:
        return (base_time + datetime.timedelta(seconds=offset_seconds)).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )

    events = []
    for i in range(4):
        events.append(
            {
                "TimeGenerated": iso(i * 17),
                "UserPrincipalName": SYNTHETIC_USER,
                "SourceIP": SYNTHETIC_SOURCE_IP,
                "ResultType": "Failure",
                "ResultDescription": "Invalid username or password",
                "Location": "Unknown",
                "AppDisplayName": SYNTHETIC_APP,
            }
        )

    events.append(
        {
            "TimeGenerated": iso(4 * 17),
            "UserPrincipalName": SYNTHETIC_USER,
            "SourceIP": SYNTHETIC_SOURCE_IP,
            "ResultType": "Success",
            "ResultDescription": "Sign-in succeeded",
            "Location": "Unknown",
            "AppDisplayName": SYNTHETIC_APP,
        }
    )

    return events


def main() -> int:
    credential = AzureCliCredential()
    client = LogsIngestionClient(endpoint=DCE_ENDPOINT, credential=credential)

    logs = generate_bruteforce_logs()

    try:
        client.upload(rule_id=DCR_IMMUTABLE_ID, stream_name=STREAM_NAME, logs=logs)
    except HttpResponseError as e:
        print(f"Ingestion failed: {e.message}", file=sys.stderr)
        print(
            "\nCommon causes:\n"
            "  - STREAM_NAME doesn't match the DCR's streamDeclarations key\n"
            "  - the signed-in account (az login) doesn't have Monitoring "
            "Metrics Publisher on this DCR\n"
            "  - a field name/type here doesn't match the table schema",
            file=sys.stderr,
        )
        return 1

    print(f"Uploaded {len(logs)} synthetic log records to stream '{STREAM_NAME}'.")
    print("Data typically takes a few minutes to become queryable in Log Analytics.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
